site_name: "ChocoManager Docs"
copyright: Copyright &copy; 2023 dadyarri
repo_url: https://github.com/choco-manager/Backend
repo_name: choco-manager/Backend

plugins:
  - search:
      lang: 
        - en
        - ru

theme:
  name: material
  language: ru
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

nav:
  - "Главная": index.md
  - "Сервер":
      - "Сервер": server/index.md
      - "API Адресов": 
        - server/modules/addresses/index.md
        - "Список": server/modules/addresses/list.md
        - "Создание": server/modules/addresses/create.md
        - "Генерация тестовых данных": server/modules/addresses/fake.md
      - "API Городов":
        - server/modules/cities/index.md
        - "Список": server/modules/cities/list.md
        - "Создание": server/modules/cities/create.md
      - "API Клиентов": 
        - server/modules/clients/index.md
        - "Список": server/modules/clients/list.md
        - "Детали": server/modules/clients/get.md
        - "Обновление": server/modules/clients/update.md
        - "Создание": server/modules/clients/create.md
        - "Генерация тестовых данных": server/modules/clients/fake.md
      - "API Статусов Перемещения":  
        - server/modules/movementStatuses/index.md
        - "Список": server/modules/movementStatuses/list.md
        - "Создание": server/modules/movementStatuses/create.md
      - "API Заказов": server/modules/orders/index.md
      - "API Типов Цен": server/modules/priceTypes/index.md
      - "API Категорий Товара": server/modules/productCategories/index.md
      - "API Товара": server/modules/products/index.md
      - "API Поставок": server/modules/shipments/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/choco-manager
  version:
    provider: mike

