site_name: "ChocoManager Docs"
copyright: Copyright &copy; 2023 dadyarri
repo_url: https://github.com/choco-manager/Backend
repo_name: choco-manager/Backend

plugins:
  - search:
      lang: 
        - en
        - ru
  - include-markdown

theme:
  name: material
  language: ru
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

nav:
  - "Главная": index.md
  - "Сервер":
      - server/index.md
      - "API Адресов": 
        - server/modules/addresses/index.md
        - "Список": server/modules/addresses/list.md
        - "Создание": server/modules/addresses/create.md
        - "Генерация тестовых данных": server/modules/addresses/fake.md
      - "API Городов":
        - server/modules/cities/index.md
        - "Список": server/modules/cities/list.md
        - "Создание": server/modules/cities/create.md
      - "API Клиентов": 
        - server/modules/clients/index.md
        - "Список": server/modules/clients/list.md
        - "Детали": server/modules/clients/get.md
        - "Обновление": server/modules/clients/update.md
        - "Создание": server/modules/clients/create.md
        - "Генерация тестовых данных": server/modules/clients/fake.md
      - "API Статусов Перемещения":  
        - server/modules/movementStatuses/index.md
        - "Список": server/modules/movementStatuses/list.md
        - "Создание": server/modules/movementStatuses/create.md
      - "API Заказов":  
        - server/modules/orders/index.md
        - "Список": server/modules/orders/list.md
        - "Детали": server/modules/orders/get.md
        - "Создание": server/modules/orders/create.md
        - "Обновление": server/modules/orders/update.md
        - "Удаление": server/modules/orders/delete.md
        - "Восстановление": server/modules/orders/restore.md
      - "API Типов Цен":   
        - server/modules/priceTypes/index.md
        - "Список": server/modules/priceTypes/list.md
      - "API Категорий Товара":   
        - server/modules/productCategories/index.md
        - "Список": server/modules/productCategories/list.md
        - "Создание": server/modules/productCategories/create.md
      - "API Товара":   
        - server/modules/products/index.md
        - "Список": server/modules/products/list.md
        - "Детали" : server/modules/products/get.md
        - "Создание": server/modules/products/create.md
        - "Обновление": server/modules/products/update.md
        - "Удаление": server/modules/products/delete.md
        - "Восстановление": server/modules/products/restore.md
      - "API Поставок":   
        - server/modules/shipments/index.md
        - "Список": server/modules/shipments/list.md
        - "Детали" : server/modules/shipments/get.md
        - "Создание": server/modules/shipments/create.md
        - "Обновление": server/modules/shipments/update.md
        - "Удаление": server/modules/shipments/delete.md
        - "Восстановление": server/modules/shipments/restore.md

  - "Мобильное приложение":
    - mobile/index.md
  - "Маркет ВКонтакте":
    - market/index.md
  - "Веб-интерфейс":
    - web/index.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/choco-manager
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

